<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\test_api' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\test_api.php';

return $this->services['App\Controller\test_api'] = new \App\Controller\test_api();
