<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CustomApi' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\CustomApi.php';

return $this->services['App\Controller\CustomApi'] = new \App\Controller\CustomApi();
