<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLlxVvEy\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLlxVvEy/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLlxVvEy.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLlxVvEy\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLlxVvEy\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'LlxVvEy',
    'container.build_id' => 'b9e2f6b9',
    'container.build_time' => 1523004783,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLlxVvEy');
