<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ0yqjAU\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ0yqjAU/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQ0yqjAU.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQ0yqjAU\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQ0yqjAU\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Q0yqjAU',
    'container.build_id' => '56ddd29b',
    'container.build_time' => 1522852304,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ0yqjAU');
